//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorApp.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete question?.
        /// </summary>
        internal static string DELETE_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Confirmation.
        /// </summary>
        internal static string DELETE_CONFIRMATION_TITLE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while deleting question.
        /// </summary>
        internal static string DELETE_ERROR {
            get {
                return ResourceManager.GetString("DELETE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End caption text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_END_CAPTION {
            get {
                return ResourceManager.GetString("EMPTY_END_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_QUESTION_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_QUESTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start caption text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_START_CAPTION {
            get {
                return ResourceManager.GetString("EMPTY_START_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_BOX_TITLE {
            get {
                return ResourceManager.GetString("ERROR_BOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred, Please try again or contact Admin.
        /// </summary>
        internal static string GENERAL_ERROR {
            get {
                return ResourceManager.GetString("GENERAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while inserting question.
        /// </summary>
        internal static string INSERT_ERROR {
            get {
                return ResourceManager.GetString("INSERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value can&apos;t be more than.
        /// </summary>
        internal static string MAX_END_VALUE_ERROR {
            get {
                return ResourceManager.GetString("MAX_END_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of faces can&apos;t be more than.
        /// </summary>
        internal static string MAX_FACES_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("MAX_FACES_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars can&apos;t be more than.
        /// </summary>
        internal static string MAX_STARS_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("MAX_STARS_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of faces can&apos;t be less than.
        /// </summary>
        internal static string MIN_FACES_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("MIN_FACES_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Order can&apos;t be less than.
        /// </summary>
        internal static string MIN_ORDER_ERROR {
            get {
                return ResourceManager.GetString("MIN_ORDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars can&apos;t be less than.
        /// </summary>
        internal static string MIN_STARS_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("MIN_STARS_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value can&apos;t be less than.
        /// </summary>
        internal static string MIN_START_VALUE_ERROR {
            get {
                return ResourceManager.GetString("MIN_START_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        internal static string QUESTION_TYPE_SLIDER {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        internal static string QUESTION_TYPE_SMILEY {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_SMILEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        internal static string QUESTION_TYPE_STARS {
            get {
                return ResourceManager.GetString("QUESTION_TYPE_STARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while refreshing list.
        /// </summary>
        internal static string REFRESH_ERROR {
            get {
                return ResourceManager.GetString("REFRESH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while selecting question.
        /// </summary>
        internal static string SELECT_ERROR {
            get {
                return ResourceManager.GetString("SELECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while sorting question.
        /// </summary>
        internal static string SORT_ERROR {
            get {
                return ResourceManager.GetString("SORT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value must be less than End value.
        /// </summary>
        internal static string START_LARGER_THAN_END_ERROR {
            get {
                return ResourceManager.GetString("START_LARGER_THAN_END_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occurred while updating question.
        /// </summary>
        internal static string UPDATE_ERROR {
            get {
                return ResourceManager.GetString("UPDATE_ERROR", resourceCulture);
            }
        }
    }
}
