//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorEntities.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End caption text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_END_CAPTION_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_END_CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_END_VALUE_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_END_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of  faces can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_FACES_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_FACES_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question order can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_ORDER_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_ORDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_QUESTION_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_QUESTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_STARS_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_STARS_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start caption text can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_START_CAPTION_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_START_CAPTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value can&apos;t be empty.
        /// </summary>
        internal static string EMPTY_START_VALUE_ERROR {
            get {
                return ResourceManager.GetString("EMPTY_START_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Caption Length must be between 1 and 25.
        /// </summary>
        internal static string END_CAPTION_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("END_CAPTION_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End value must be between Start value and 100.
        /// </summary>
        internal static string END_VALUE_ERROR {
            get {
                return ResourceManager.GetString("END_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of faces must between 2 and 5.
        /// </summary>
        internal static string FACES_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("FACES_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question order must be larger than 0.
        /// </summary>
        internal static string ORDER_ERROR {
            get {
                return ResourceManager.GetString("ORDER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question text length must be between 1 and 100.
        /// </summary>
        internal static string QUESTION_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("QUESTION_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of stars must between 1 and 10.
        /// </summary>
        internal static string STARS_NUMBER_ERROR {
            get {
                return ResourceManager.GetString("STARS_NUMBER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start caption length must be between 1 and 25.
        /// </summary>
        internal static string START_CAPTION_LENGTH_ERROR {
            get {
                return ResourceManager.GetString("START_CAPTION_LENGTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value must be between 1 and End value.
        /// </summary>
        internal static string START_VALUE_ERROR {
            get {
                return ResourceManager.GetString("START_VALUE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources {
            get {
                return ResourceManager.GetString("StringResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_ar {
            get {
                return ResourceManager.GetString("StringResources_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StringResources_ar_Designer {
            get {
                return ResourceManager.GetString("StringResources_ar_Designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------
        ///// &lt;auto-generated&gt;
        /////     This code was generated by a tool.
        /////     Runtime Version:4.0.30319.42000
        /////
        /////     Changes to this file may cause incorrect behavior and will be lost if
        /////     the code is regenerated.
        ///// &lt;/auto-generated&gt;
        /////------------------------------------------------------------------------------
        ///
        ///namespace SurveyConfiguratorApp.Properties {
        ///    using System;
        ///    
        ///    
        ///    /// &lt;summary&gt;
        ///    ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringResources_Designer {
            get {
                return ResourceManager.GetString("StringResources_Designer", resourceCulture);
            }
        }
    }
}
