//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Captions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Captions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorWeb.Properties.Captions", typeof(Captions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ACTIONS {
            get {
                return ResourceManager.GetString("ACTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ADD_BUTTON {
            get {
                return ResourceManager.GetString("ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربي.
        /// </summary>
        public static string ARABIC_LANGUAGE {
            get {
                return ResourceManager.GetString("ARABIC_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ASCENDING {
            get {
                return ResourceManager.GetString("ASCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Question.
        /// </summary>
        public static string CREATE_QUESTION {
            get {
                return ResourceManager.GetString("CREATE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DEFAULT {
            get {
                return ResourceManager.GetString("DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete question?.
        /// </summary>
        public static string DELETE_CONFIRMATION_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Question.
        /// </summary>
        public static string DELETE_CONFIRMATION_TITLE {
            get {
                return ResourceManager.GetString("DELETE_CONFIRMATION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string DESCENDING {
            get {
                return ResourceManager.GetString("DESCENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT {
            get {
                return ResourceManager.GetString("EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string EDIT_PAGE_TITLE {
            get {
                return ResourceManager.GetString("EDIT_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        public static string EDIT_QUESTION {
            get {
                return ResourceManager.GetString("EDIT_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ENGLISH_LANGUAGE {
            get {
                return ResourceManager.GetString("ENGLISH_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Questions.
        /// </summary>
        public static string LIST_PAGE_HEADER {
            get {
                return ResourceManager.GetString("LIST_PAGE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Questions List.
        /// </summary>
        public static string LIST_PAGE_TITLE {
            get {
                return ResourceManager.GetString("LIST_PAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value Caption.
        /// </summary>
        public static string QUESTION_END_CAPTION {
            get {
                return ResourceManager.GetString("QUESTION_END_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Value.
        /// </summary>
        public static string QUESTION_END_VALUE {
            get {
                return ResourceManager.GetString("QUESTION_END_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Faces.
        /// </summary>
        public static string QUESTION_FACES_NUMBER {
            get {
                return ResourceManager.GetString("QUESTION_FACES_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string QUESTION_ORDER {
            get {
                return ResourceManager.GetString("QUESTION_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Stars.
        /// </summary>
        public static string QUESTION_STARS_NUMBER {
            get {
                return ResourceManager.GetString("QUESTION_STARS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value Caption.
        /// </summary>
        public static string QUESTION_START_CAPTION {
            get {
                return ResourceManager.GetString("QUESTION_START_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Value.
        /// </summary>
        public static string QUESTION_START_VALUE {
            get {
                return ResourceManager.GetString("QUESTION_START_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Text.
        /// </summary>
        public static string QUESTION_TEXT {
            get {
                return ResourceManager.GetString("QUESTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string QUESTION_TYPE {
            get {
                return ResourceManager.GetString("QUESTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE_BUTTON {
            get {
                return ResourceManager.GetString("SAVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider Question.
        /// </summary>
        public static string SLIDER_QUESTION {
            get {
                return ResourceManager.GetString("SLIDER_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley Question.
        /// </summary>
        public static string SMILEY_QUESTION {
            get {
                return ResourceManager.GetString("SMILEY_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string SORT {
            get {
                return ResourceManager.GetString("SORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars Question.
        /// </summary>
        public static string STARS_QUESTION {
            get {
                return ResourceManager.GetString("STARS_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slider.
        /// </summary>
        public static string TYPE_SLIDER {
            get {
                return ResourceManager.GetString("TYPE_SLIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        public static string TYPE_SMILEY {
            get {
                return ResourceManager.GetString("TYPE_SMILEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string TYPE_STARS {
            get {
                return ResourceManager.GetString("TYPE_STARS", resourceCulture);
            }
        }
    }
}
