//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyConfiguratorWeb.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SurveyConfiguratorWeb.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting question.
        /// </summary>
        internal static string DELETE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("DELETE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Error.
        /// </summary>
        internal static string DELETE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("DELETE_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, Please try again or contact Admin.
        /// </summary>
        internal static string GENERAL_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("GENERAL_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string GENERAL_ERROR_TITLE {
            get {
                return ResourceManager.GetString("GENERAL_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting question.
        /// </summary>
        internal static string INSERT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("INSERT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Error.
        /// </summary>
        internal static string INSERT_ERROR_TITLE {
            get {
                return ResourceManager.GetString("INSERT_ERROR_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested question id is invalid.
        /// </summary>
        internal static string INVALID_QUESTION_ID_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_QUESTION_ID_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id.
        /// </summary>
        internal static string INVALID_QUESTION_ID_TITLE {
            get {
                return ResourceManager.GetString("INVALID_QUESTION_ID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question type you have selected is invalid.
        /// </summary>
        internal static string INVALID_TYPE_MESSAGE {
            get {
                return ResourceManager.GetString("INVALID_TYPE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid question type.
        /// </summary>
        internal static string INVALID_TYPE_TITLE {
            get {
                return ResourceManager.GetString("INVALID_TYPE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested question could not be found.
        /// </summary>
        internal static string QUESTION_NOT_FOUND_MESSAGE {
            get {
                return ResourceManager.GetString("QUESTION_NOT_FOUND_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Not Found.
        /// </summary>
        internal static string QUESTION_NOT_FOUND_TITLE {
            get {
                return ResourceManager.GetString("QUESTION_NOT_FOUND_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start value must be less than End value.
        /// </summary>
        internal static string START_LARGER_THAN_END_ERROR {
            get {
                return ResourceManager.GetString("START_LARGER_THAN_END_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating question.
        /// </summary>
        internal static string UPDATE_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("UPDATE_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        internal static string UPDATE_ERROR_TITLE {
            get {
                return ResourceManager.GetString("UPDATE_ERROR_TITLE", resourceCulture);
            }
        }
    }
}
